In [1]:
import numpy as np

### Creating ARRAY using numpy

In [6]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
arr2 = np.array([1,2,3,4,5, 6])

arr2.reshape(2, 3) # 2 rows, 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 2D Array
arr2 = np.array([[1,2,3,4,5,6], [-1, -2, -3, -4, -5, -6]])
print(arr2.shape)

print(arr2)

(2, 6)
[[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


In [18]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
## Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Attributes of Numpy

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  
print("NUmber of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
NUmber of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


### Vectorized Operation

In [35]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element Wise Addition
print("Addition:", arr1 + arr2)

# Element Wise Subtraction
print("Subtraction:", arr1 - arr2)

# Element Wise Multiplication
print("Multiplication:", arr1 * arr2)

# Element Wise Division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [40]:
# Universal Function
arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))


# exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### Array Slicing and Indexing

In [43]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array: \n", arr)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
print(arr[0][0])
print(arr[0:2, 2:])

1
[[3 4]
 [7 8]]


In [52]:
print(arr[1:, 2:])

[[ 7  8]
 [11 12]]


In [55]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


### Modify Elements

In [59]:
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [61]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


## STATISTICS --> NORMALIZATION

In [64]:
# To have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
print("std", std_dev)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

std 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [68]:
# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("median:", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 3.0
median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


### Logical Operation

In [77]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])